import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/navbar";
import Footer from "../components/footer/footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.min.css";
import RootClient from "./RootClient";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Do studio",
  description: "Generated by Dostudio",
  icons: {
    icon: ["/src/app/favicon.ico"],
    apple: ["/src/app/apple-touch-icon.png?v=4"],
    shortcut: ["/src/app/apple-touch-icon.png"],
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ToastContainer position="bottom-right" />
        <div className="2xl:max-w-[1800px] mx-auto">
        <RootClient>

          <Navbar />
          {children}
          <Footer />
        </RootClient>
        </div>
      </body>
    </html>
  );
}
